"""
Django settings for sgo_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import shutil
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r0wjm3jz%$dbm46i2p7dkk7+g^9^w5zuwquk6=8t(e*_^$%#vn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'core',
    'flota',
    'operaciones',
    'reportes',
    'mantencion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sgo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sgo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DB_PATH = BASE_DIR / 'db.sqlite3'

# Vercel env is read-only, copy DB to /tmp so we can write to it during the lambda lifecycle
if os.environ.get('VERCEL'):
    TMP_DB_PATH = Path('/tmp/db.sqlite3')
    if not TMP_DB_PATH.exists():
        shutil.copy2(DB_PATH, TMP_DB_PATH)
    DB_PATH = TMP_DB_PATH

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

# La operación ocurre en Chile y la planilla se lleva en hora local.
# Con USE_TZ la base sigue guardando UTC; esto solo decide cómo se
# interpreta "hoy". Dejarlo en UTC hacía que el día cambiara a las
# 20:00 o 21:00 hora chilena, justo en medio del turno de tarde.
TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Las migraciones existentes se generaron con BigAutoField. Sin este
# ajuste Django asume AutoField y propone degradar todas las claves
# primarias, además de emitir los avisos models.W042.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ── CORS ────────────────────────────────────────────────────────
# En producción el frontend y la API comparten origen (vercel.json
# reescribe /api al backend) y en local el proxy de Vite hace lo mismo,
# así que CORS casi no entra en juego. Se declara igual para quien
# levante el frontend sin proxy.
#
# CORS_ALLOW_ALL_ORIGINS se retiró: con credenciales el navegador
# rechaza el comodín, y permitir cualquier origen con cookies de sesión
# habilita robo de sesión desde un sitio de terceros.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True

# Orígenes de confianza para el token CSRF.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://gestionbuses.vercel.app',
    'https://*.vercel.app',
]

# El SPA lee la cookie CSRF con JavaScript para reenviarla en la
# cabecera, así que no puede ser HttpOnly. La cookie de sesión sí lo es
# (por defecto), que es la que realmente autentica.
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# ── DRF ─────────────────────────────────────────────────────────
# Autenticación por sesión: el frontend es same-origin, así que la
# cookie viaja sola y no hay que guardar un token en localStorage.
# Todo endpoint exige sesión salvo que declare AllowAny.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'core.permissions.TienePersona',
    ],
}
