# Generated by Django 5.1.4 on 2026-09-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0001_initial'),
        ('operaciones', '0002_ciudad_ruta_postura_asignaciontripulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Checklist',
                'verbose_name_plural': 'Categorías de Checklist',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('SALIDA', 'Preventivo de salida'), ('LLEGADA', 'Recepción en terminal')], default='SALIDA', max_length=10)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('COMPLETADO', 'Completado')], default='EN_CURSO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='flota.bus')),
                ('postura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='operaciones.postura')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='operaciones.persona')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('critico', models.BooleanField(default=False, help_text='Si falla, el bus queda fuera de servicio de inmediato')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mantencion.categoriachecklist')),
            ],
            options={
                'verbose_name': 'Ítem de Checklist',
                'verbose_name_plural': 'Ítems de Checklist',
                'ordering': ['categoria__orden', 'orden', 'id'],
                'unique_together': {('categoria', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=6)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_REVISION', 'En revisión'), ('RESUELTO', 'Resuelto'), ('DESCARTADO', 'Descartado')], default='ABIERTO', max_length=12)),
                ('origen', models.CharField(choices=[('CHECKLIST', 'Checklist'), ('RUTA', 'Reportado en ruta')], default='RUTA', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='flota.bus')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='mantencion.checklist')),
                ('postura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='operaciones.postura')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='operaciones.persona')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantencion.itemchecklist')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OK', 'Conforme'), ('FALLA', 'Con falla'), ('NA', 'No aplica')], max_length=5)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='mantencion.checklist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantencion.itemchecklist')),
            ],
            options={
                'verbose_name': 'Respuesta de Checklist',
                'verbose_name_plural': 'Respuestas de Checklist',
                'ordering': ['item__categoria__orden', 'item__orden'],
                'unique_together': {('checklist', 'item')},
            },
        ),
    ]
