# Generated by Django 5.1.4 on 2026-09-02 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
        ('mantencion', '0001_initial'),
        ('operaciones', '0003_alter_asignaciontripulacion_rol_en_viaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('especialidad', models.CharField(choices=[('MOTOR', 'Motor'), ('FRENOS', 'Frenos'), ('SUSPENSION', 'Suspensión'), ('ELECTRICO', 'Eléctrico'), ('CARROCERIA', 'Carrocería'), ('GENERAL', 'General')], default='GENERAL', max_length=12)),
                ('tipo', models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('PREVENTIVO', 'Preventivo')], default='CORRECTIVO', max_length=10)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5)),
                ('estado', models.CharField(choices=[('SIN_ASIGNAR', 'Sin asignar'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='SIN_ASIGNAR', max_length=11)),
                ('pozo', models.CharField(blank=True, max_length=20)),
                ('diagnostico', models.TextField(blank=True, help_text='Qué se hizo para resolver el trabajo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='flota.bus')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantencion.incidente')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='operaciones.persona')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-creado_en'],
            },
        ),
    ]
