# Generated by Django 5.1.4 on 2026-09-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0002_ordentrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
