# Generated by Django 5.2.17 on 2026-09-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0003_alter_incidente_codigo_alter_ordentrabajo_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='momento',
        ),
        migrations.AlterField(
            model_name='incidente',
            name='gravedad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], help_text='Nulo mientras Mantención no la haya clasificado', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='especialidad',
            field=models.CharField(choices=[('MECANICO', 'Mecánico'), ('ELECTRICO', 'Eléctrico'), ('CARROCERO', 'Carrocero'), ('VULCANIZADOR', 'Vulcanizador'), ('INFORMATICA', 'Informática')], default='MECANICO', max_length=12),
        ),
    ]
