# Generated by Django 5.2.17 on 2026-09-03 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0008_alter_asignaciontripulacion_rol_en_viaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Te asignaron un servicio'), ('DESASIGNACION', 'Te quitaron de un servicio'), ('CAMBIO_BUS', 'Cambió la máquina de tu servicio'), ('CORRIDA', 'Corrida en un servicio tuyo')], max_length=15)),
                ('titulo', models.CharField(max_length=120)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('ruta', models.CharField(default='/', max_length=60)),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='operaciones.persona')),
                ('postura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='operaciones.postura')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['persona', 'leida', '-creado_en'], name='core_notifi_persona_f791a5_idx')],
            },
        ),
    ]
