# Generated by Django 6.1 on 2026-09-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('patente', models.CharField(max_length=15, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_SERVICIO', 'En Servicio'), ('MANTENIMIENTO', 'Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=20)),
                ('servicio', models.CharField(choices=[('SC', 'Semi Cama'), ('SLC', 'Salón Cama'), ('CP', 'Cama Premium'), ('MIN', 'Minero')], max_length=10)),
                ('pozo', models.CharField(blank=True, max_length=20, null=True)),
                ('proxima_postura', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
