# Generated by Django 6.1 on 2026-09-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente')], default='CONDUCTOR', max_length=20)),
                ('tipo', models.CharField(choices=[('TITULAR', 'Titular'), ('RELEVO', 'Relevo')], default='TITULAR', max_length=20)),
                ('horas_hoy', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('semaforo', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], default='verde', max_length=15)),
                ('razon_bloqueo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
