# Generated by Django 6.1 on 2026-09-02 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_estimada', models.DecimalField(decimal_places=1, help_text='Horas estimadas', max_digits=4)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rutas_destino', to='operaciones.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rutas_origen', to='operaciones.ciudad')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Postura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('estado', models.CharField(choices=[('LISTA', 'Lista'), ('ALERTA', 'Alerta'), ('PROBLEMA', 'Problema'), ('EN_CURSO', 'En Curso'), ('COMPLETA', 'Completa')], default='LISTA', max_length=20)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.ruta')),
            ],
            options={
                'verbose_name': 'Postura',
                'verbose_name_plural': 'Posturas',
                'ordering': ['fecha', 'hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_viaje', models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente')], max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.persona')),
                ('postura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion', to='operaciones.postura')),
            ],
            options={
                'verbose_name': 'Asignación de Tripulación',
                'verbose_name_plural': 'Asignaciones de Tripulación',
                'unique_together': {('postura', 'persona')},
            },
        ),
    ]
