# Generated by Django 5.1.4 on 2026-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_ciudad_ruta_postura_asignaciontripulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontripulacion',
            name='rol_en_viaje',
            field=models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecánico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecánico')], default='CONDUCTOR', max_length=20),
        ),
    ]
