# Generated by Django 5.1.4 on 2026-09-02 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_asignaciontripulacion_rol_en_viaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignaciontripulacion',
            name='rol_en_viaje',
            field=models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecánico'), ('JEFE_OPERACIONES', 'Jefe de Operaciones'), ('JEFE_MECANICOS', 'Jefe de Mecánicos'), ('MONITOREO', 'Sala de Monitoreo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecánico'), ('JEFE_OPERACIONES', 'Jefe de Operaciones'), ('JEFE_MECANICOS', 'Jefe de Mecánicos'), ('MONITOREO', 'Sala de Monitoreo')], default='CONDUCTOR', max_length=20),
        ),
    ]
