# Generated by Django 5.1.4 on 2026-09-02 20:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
        ('operaciones', '0004_persona_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postura',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,8}$', 'El código de postura debe ser numérico, de 4 a 8 dígitos (ej. 112218).')]),
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('bus_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas_como_original', to='flota.bus')),
                ('bus_sustituto', models.ForeignKey(blank=True, help_text='Nulo si aún no se consigue reemplazo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridas_como_sustituto', to='flota.bus')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas', to='operaciones.persona')),
                ('posturas', models.ManyToManyField(blank=True, related_name='corridas', to='operaciones.postura')),
            ],
            options={
                'verbose_name': 'Corrida',
                'verbose_name_plural': 'Corridas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
