# Generated by Django 5.1.4 on 2026-09-02 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_alter_postura_codigo_corrida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postura',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'El código de postura son seis dígitos numéricos (ej. 112218).')]),
        ),
    ]
