# Generated by Django 5.1.4 on 2026-09-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_postura_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductores_por_servicio', models.PositiveSmallIntegerField(default=2, help_text='Cuántos conductores lleva cada servicio')),
                ('asistentes_por_servicio', models.PositiveSmallIntegerField(default=1, help_text='Cuántos asistentes lleva cada servicio')),
                ('horas_conduccion_max', models.DecimalField(decimal_places=1, default=5.0, help_text='Máximo de horas continuas al volante', max_digits=4)),
                ('horas_conduccion_aviso', models.DecimalField(decimal_places=1, default=4.0, help_text='A partir de cuántas horas se avisa (semáforo amarillo)', max_digits=4)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operaciones.persona')),
            ],
            options={
                'verbose_name': 'Parámetros del sistema',
                'verbose_name_plural': 'Parámetros del sistema',
            },
        ),
    ]
