# Generated by Django 5.1.4 on 2026-09-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontripulacion',
            name='rol_en_viaje',
            field=models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecánico'), ('JEFE_OPERACIONES', 'Jefe de Operaciones'), ('JEFE_MECANICOS', 'Jefe de Mecánicos'), ('MONITOREO', 'Sala de Monitoreo'), ('ADMIN', 'Administrador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('CONDUCTOR', 'Conductor'), ('ASISTENTE', 'Asistente'), ('MECANICO', 'Mecánico'), ('JEFE_OPERACIONES', 'Jefe de Operaciones'), ('JEFE_MECANICOS', 'Jefe de Mecánicos'), ('MONITOREO', 'Sala de Monitoreo'), ('ADMIN', 'Administrador')], default='CONDUCTOR', max_length=20),
        ),
    ]
