# Generated by Django 5.2.17 on 2026-09-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_alter_asignaciontripulacion_rol_en_viaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='horas_conduccion_aviso',
        ),
        migrations.RemoveField(
            model_name='parametros',
            name='horas_conduccion_max',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='horas_hoy',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='razon_bloqueo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='semaforo',
        ),
    ]
