# Generated by Django 5.2.17 on 2026-09-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
        ('operaciones', '0009_remove_parametros_horas_conduccion_aviso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corrida',
            name='bus_sustituto',
        ),
        migrations.RemoveField(
            model_name='corrida',
            name='posturas',
        ),
        migrations.AddField(
            model_name='corrida',
            name='bus_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corridas_que_cerro', to='flota.bus'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='postura_origen',
            field=models.ForeignKey(help_text='El servicio que quedó sin máquina', on_delete=django.db.models.deletion.PROTECT, related_name='corridas_originadas', to='operaciones.postura'),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='bus_original',
            field=models.ForeignKey(help_text='La máquina que se cayó y disparó la cadena', on_delete=django.db.models.deletion.PROTECT, related_name='corridas_como_original', to='flota.bus'),
        ),
        migrations.CreateModel(
            name='MovimientoCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(help_text='Posición en la cadena, empezando por el servicio caído')),
                ('bus_entrante', models.ForeignKey(blank=True, help_text='La que lo cubre ahora. Nulo: queda esperando.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_como_entrante', to='flota.bus')),
                ('bus_saliente', models.ForeignKey(blank=True, help_text='La máquina que tenía este servicio antes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_como_saliente', to='flota.bus')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='operaciones.corrida')),
                ('postura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_corrida', to='operaciones.postura')),
            ],
            options={
                'verbose_name': 'Movimiento de corrida',
                'verbose_name_plural': 'Movimientos de corrida',
                'ordering': ['corrida', 'orden'],
                'unique_together': {('corrida', 'postura')},
            },
        ),
    ]
