# Generated by Django 5.2.17 on 2026-09-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_remove_corrida_bus_sustituto_remove_corrida_posturas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontripulacion',
            name='rol_en_viaje',
            field=models.CharField(choices=[('JEFE_MAQUINA', 'Jefe de máquina'), ('SEGUNDO_CONDUCTOR', '2° conductor'), ('AUXILIAR', 'Auxiliar')], help_text='El puesto en este viaje, no el cargo de la persona', max_length=20),
        ),
    ]
