# Generated by Django 5.2.17 on 2026-09-03 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_alter_asignaciontripulacion_rol_en_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('dias_trabajo', models.PositiveSmallIntegerField()),
                ('dias_descanso', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo de turno',
                'verbose_name_plural': 'Ciclos de turno',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(help_text='Primer día de trabajo del ciclo vigente')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='operaciones.cicloturno')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='operaciones.persona')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['persona__nombre'],
            },
        ),
    ]
