# Generated by Django 5.2.17 on 2026-09-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_cicloturno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='debe_cambiar_clave',
            field=models.BooleanField(default=False),
        ),
    ]
